CREATE TABLE IF NOT EXISTS messages (
	id SERIAL PRIMARY KEY NOT NULL,
	email VARCHAR(255) NOT NULL,
	message VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS data_users(
	id SERIAL PRIMARY KEY NOT NULL,
	card_number VARCHAR(255) NOT NULL,
	validity VARCHAR(255) NOT NULL,
	owner_name VARCHAR(255) NOT NULL,
	cvv_code VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	phone VARCHAR(255) NOT NULL
);